PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE POST(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
TITLE CHAR(50) NOT NULL,
CATEGORYA CHAR(50) NOT NULL,
CATEGORYB CHAR(50),
CATEGORYC CHAR(50),
CATEGORYD CHAR(50),
CONTENT TEXT NOT NULL,
DATETIME CHAR(30) NOT NULL
);
COMMIT;
